### ISSUE TITLE
Removing and readding platform does not work

### ISSUE THREAD

**Issue by DavidStrausz** [getsentry/sentry-cordova#10]
Because the cordova plugin "cordova-plugin-sentry" and the npm-package "@sentry/cordova" live under the same package, cordova and npm get into trouble when trying to restore a platform.

This can be fixed by publishing the cordova-plugin under a new name on npm. "cordova-plugin-sentry" is already taken by another package so a slight name change would be necessary.

**Comment by HazAT** [comment]
Thank you for highlighting this!
I've up'd the dependency for cordova to `8.0.0` since scoped packges seems to be fixed there.
Stay tuned for the next release.

**Comment by HazAT** [comment]
Well actually it is not yet fully working, so we have to live with it for a while now.

**Comment by llamaluvr** [comment]
I'm trying to run an app that just had Sentry for Cordova added by another user and am getting the following when running `npm install`:

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@sentry/cordova@~0.5.3" as it does not contain a package.json file.
```

Is this the same issue?

If so, what is the recommended workaround?

Thank you!

**Comment by HazAT** [comment]
Yeah, it is the same issue and sadly there is currently no workaround for this other than us renaming the package (which we not gonna do) or Cordova releasing a bugfix.
But to be fair, this error is more of an info since it shouldn't break anything.
Here is the issue in their Jira:
https://issues.apache.org/jira/browse/CB-10239?jql=labels%20%3D%20cordova-8.0.0

**Comment by llamaluvr** [comment]
This error prevents my node modules from being installed.
