### ISSUE TITLE
Sentry.captureException crashes iOS app if not provided an Error object

### ISSUE THREAD

**Issue by alexhisen** [getsentry/sentry-cordova#111]
iOS 12, sentry-cordova v0.13.1. If you call Sentry.captureException({ name: 'test', message: 'test' }) it crashes the app with:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM objectAtIndexedSubscript:]: unrecognized selector sent to instance 0x282f221c0'

Android doesn't have this problem.

**Comment by wcjord** [comment]
I've got the same bug and have had to totally remove Sentry as a result. I'd love to see this resolved so we can come back to Sentry - currently looking for alternatives.

**Comment by alexhisen** [comment]
try/catch around Sentry is not going to prevent the crash at the native layer. A workaround is to sanitize the input provided to Sentry, i.e.:
Sentry.captureException(e.stack ? e : new Error(e.message || e));

**Comment by wcjord** [comment]
@alexhisen I don't think that's possible because the error is coming from a plugin. We could talk to the plugin but Sentry's whole raison d'etre is too catch things that haven't been caught, no? So if it crashes the whole app (for a bug currently not crashing the app) then it's not really worth it.

**Comment by alexhisen** [comment]
If I understand it correctly, IonicErrorHandler intercepts console.error() calls. That's not really an uncaught exception. Those are caught by Sentry via window.onerror and always have a real Error object so they won't cause the app to crash. Your issue (just like ours) most likely is some code doing console.error({object that's not an Error object with a stack property}). We don't use Ionic but I'd imagine if you modify https://github.com/getsentry/sentry-cordova/blob/master/src/js/Ionic/SentryIonicErrorHandler.ts to do something along the lines of Sentry.captureException(e.stack ? e : new Error(e.message || e)), it will stop your app from crashing.

**Comment by wcjord** [comment]
Ah so in the plugin code. It's above my pay grade to propose but I'll try it out if you think that'd work! Working on some other stuff at the moment but I'll give it a shot soon and report back.

**Comment by wcjord** [comment]
@alexhisen Hey I tried to do what you suggested but I couldn't find that file!

Here's the file structure in the module that I've got.
<img width="397" alt="screen shot 2019-02-18 at 12 03 58 pm" src="https://user-images.githubusercontent.com/32568597/52968713-554dd100-33ae-11e9-922d-60bc948edf09.png">

We're talking about the same thing right? From package.json:
```
"dependencies": {
    ...
    "sentry-cordova": "^0.13.1",
  },
  "devDependencies": {
   ...
    "@sentry/webpack-plugin": "^1.6.2",
  },
  "cordovaPlugins": [
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "Learn any language while texting your friends",
  "cordova": {
    "platforms": [
      "browser",
      "ios",
      "android"
    ],
    "plugins": {
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-nativeaudio": {},
      "cordova-plugin-nativestorage": {},
      "cordova-sqlite-storage": {},
      "cordova-plugin-facebook4": {
        "APP_ID": "163763957667018",
        "APP_NAME": "Pangea.chat",
        "ANDROID_SDK_VERSION": "4.+",
        "FACEBOOK_ANDROID_SDK_VERSION": "4.+"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-media": {
        "KEEP_AVAUDIOSESSION_ALWAYS_ACTIVE": "NO"
      },
      "cordova-plugin-file": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-local-notification": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-fcm-with-dependecy-updated": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-network-information": {},
      "cordova-android-support-gradle-release": {
        "ANDROID_SUPPORT_VERSION": "27.1.0"
      },
      "sentry-cordova": {}
    }
  }

```

**Comment by alexhisen** [comment]
The js code is in the dist/js folder but it's all compiled and minified probably. Your best bet is to fork this plugin and modify the src/js/Ionic/SentryIonicErrorHandler.ts and build it. If this fixes your problem, you could then submit a PR to this plugin from your fork.

**Comment by AdrienV** [comment]
Hi guys,

I get a similar error & crash when I try run on iOs : 

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM objectAtIndexedSubscript:]: unrecognized selector sent to instance 0x2832f4ce0'
*** First throw call stack:
(0x203245ea4 0x202415a50 0x20315eb14 0x20324b7bc 0x20324d46c 0x105c316f0 0x10507adc4 0x105cd7824 0x105cd8dc8 0x105cdbc90 0x105cea1dc 0x105ceabc8 0x202e6117c 0x202e63cec)
libc++abi.dylib: terminating with uncaught exception of type NSException`

Any information to solve it ?

**Comment by rgharris** [comment]
> iOS 12, sentry-cordova v0.13.1. If you call Sentry.captureException({ name: 'test', message: 'test' }) it crashes the app with:
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM objectAtIndexedSubscript:]: unrecognized selector sent to instance 0x282f221c0'
> 
> Android doesn't have this problem.

We were seeing crashes of our Ionic app on iOS as well due to Sentry logging JS errors. One particular issue that makes it easy to reproduce is to get a non 200 status from a CORS preflight OPTIONS request prior to a GET (you can also just take your device offline prior to the preflight request and you will get the same result, this is what we're seeing in production). Here is a [Stack Overflow answer](https://stackoverflow.com/a/14507670/1684623) about `status 0`. We are using [WKWebView](https://github.com/ionic-team/cordova-plugin-ionic-webview) as recommended by Ionic, we end up getting this "error":
```
{
  "_body": { 
    "isTrusted": true
  },
  "status": 0,
  "ok": false,
  "statusText": "",
  "headers": {},
  "type": 3,
  "url": null
}
```

I've worked around via the following two changes. It isn't ideal, but does seem to prevent these native crashes and we are still able to report most errors to Sentry (via our wire up in `SentryIonicErrorHandler` rather than automatically by Sentry) from what I can tell so far. 

1. Remove problematic [Sentry JS SDK Integrations](https://docs.sentry.io/platforms/javascript/?platform=browser#sdk-integrations). A better alternative to this might be to augment/replace these implementations by adding some safeguard code directly to them.

```
Sentry.init({ 
  dsn: '***',
  environment: 'Example',
  integrations: integrations => {
    // integrations will be all default integrations
    // remove problematic integrations causing native crashes on iOS
    return integrations.filter(integration => integration.name !== 'GlobalHandlers' && integration.name !== "TryCatch");
  },
});
```

2. Update [`SentryIonicErrorHandler`](https://docs.sentry.io/platforms/javascript/ionic/) to have some safeguards for errors that aren't a JS `Error`:
```
import { IonicErrorHandler } from 'ionic-angular';

import * as Sentry from 'sentry-cordova';

export class SentryIonicErrorHandler extends IonicErrorHandler {
  handleError(error) {
    super.handleError(error);

    if (!error) { return; }

    try {
      const originalError = error.originalError || error;
      Sentry.captureException(originalError.stack ? originalError : new Error(originalError.message || originalError));
    } catch (e) {
      console.error(e);
    }
  }
}
```

I'm not sure if this is more of an issue on the side of the weird "error" we get due to the CORS preflight request failing or Sentry. But it seems like Sentry should be able to handle errors in unexpected formats.

I have dug through a lot of code in sentry-cordova, sentry-javascript, and sentry-cocoa but haven't been able to pinpoint exactly how this could be fixed in the Sentry source. But I suspect that the use of [`SentryJavaScriptBridgeHelper createSentryEventFromJavaScriptEvent:jsonEvent` in `SentryCordova.m`](https://github.com/getsentry/sentry-cordova/blob/master/src/ios/SentryCordova.m#L54) is the issue. A fix may be to add safeguards in [`createSentryEventFromJavaScriptEvent` in `SentryJavaScriptBridgeHelper.m`](https://github.com/getsentry/sentry-cocoa/blob/c7f5884e791d46df48e003558c30361574ec8b57/Sources/Sentry/SentryJavaScriptBridgeHelper.m#L117). But, it may be cleaner to add a fix further upstream so that an invalid `Exception` isn't passed in at all to start with.


Ionic environment info:
```
Ionic:

   ionic (Ionic CLI)  : 4.7.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.0, (and 21 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 7.0.0
   NodeJS     : v10.10.0 
   npm        : 6.5.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by ErnestStaug** [comment]
> > iOS 12, sentry-cordova v0.13.1. If you call Sentry.captureException({ name: 'test', message: 'test' }) it crashes the app with:
> > *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM objectAtIndexedSubscript:]: unrecognized selector sent to instance 0x282f221c0'
> > Android doesn't have this problem.
> 
> We were seeing crashes of our Ionic app on iOS as well due to Sentry logging JS errors. One particular issue that makes it easy to reproduce is to get a non 200 status from a CORS preflight OPTIONS request prior to a GET (you can also just take your device offline prior to the preflight request and you will get the same result, this is what we're seeing in production). Here is a [Stack Overflow answer](https://stackoverflow.com/a/14507670/1684623) about `status 0`. We are using [WKWebView](https://github.com/ionic-team/cordova-plugin-ionic-webview) as recommended by Ionic, we end up getting this "error":
> 
> ```
> {
>   "_body": { 
>     "isTrusted": true
>   },
>   "status": 0,
>   "ok": false,
>   "statusText": "",
>   "headers": {},
>   "type": 3,
>   "url": null
> }
> ```
> I've worked around via the following two changes. It isn't ideal, but does seem to prevent these native crashes and we are still able to report most errors to Sentry (via our wire up in `SentryIonicErrorHandler` rather than automatically by Sentry) from what I can tell so far.
> 
> 1. Remove problematic [Sentry JS SDK Integrations](https://docs.sentry.io/platforms/javascript/?platform=browser#sdk-integrations). A better alternative to this might be to augment/replace these implementations by adding some safeguard code directly to them.
> 
> ```
> Sentry.init({ 
>   dsn: '***',
>   environment: 'Example',
>   integrations: integrations => {
>     // integrations will be all default integrations
>     // remove problematic integrations causing native crashes on iOS
>     return integrations.filter(integration => integration.name !== 'GlobalHandlers' && integration.name !== "TryCatch");
>   },
> });
> ```
> 1. Update [`SentryIonicErrorHandler`](https://docs.sentry.io/platforms/javascript/ionic/) to have some safeguards for errors that aren't a JS `Error`:
> 
> ```
> import { IonicErrorHandler } from 'ionic-angular';
> 
> import * as Sentry from 'sentry-cordova';
> 
> export class SentryIonicErrorHandler extends IonicErrorHandler {
>   handleError(error) {
>     super.handleError(error);
> 
>     if (!error) { return; }
> 
>     try {
>       const originalError = error.originalError || error;
>       Sentry.captureException(originalError.stack ? originalError : new Error(originalError.message || originalError));
>     } catch (e) {
>       console.error(e);
>     }
>   }
> }
> ```
> I'm not sure if this is more of an issue on the side of the weird "error" we get due to the CORS preflight request failing or Sentry. But it seems like Sentry should be able to handle errors in unexpected formats.
> 
> I have dug through a lot of code in sentry-cordova, sentry-javascript, and sentry-cocoa but haven't been able to pinpoint exactly how this could be fixed in the Sentry source. But I suspect that the use of [`SentryJavaScriptBridgeHelper createSentryEventFromJavaScriptEvent:jsonEvent` in `SentryCordova.m`](https://github.com/getsentry/sentry-cordova/blob/master/src/ios/SentryCordova.m#L54) is the issue. A fix may be to add safeguards in [`createSentryEventFromJavaScriptEvent` in `SentryJavaScriptBridgeHelper.m`](https://github.com/getsentry/sentry-cocoa/blob/c7f5884e791d46df48e003558c30361574ec8b57/Sources/Sentry/SentryJavaScriptBridgeHelper.m#L117). But, it may be cleaner to add a fix further upstream so that an invalid `Exception` isn't passed in at all to start with.
> 
> Ionic environment info:
> 
> ```
> Ionic:
> 
>    ionic (Ionic CLI)  : 4.7.1
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.2.2
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
>    Cordova Platforms     : android 7.1.4, ios 5.0.0
>    Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.0, (and 21 other plugins)
> 
> System:
> 
>    ios-deploy : 1.9.4
>    ios-sim    : 7.0.0
>    NodeJS     : v10.10.0 
>    npm        : 6.5.0
>    OS         : macOS Mojave
>    Xcode      : Xcode 10.1 Build version 10B61
> ```

Unfortuneteley you fixes doesn't work for me...

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString sentry_sanitize]: unrecognized selector sent to instance 0x1f693fc90'```

Still getting this issue.

**Comment by rgharris** [comment]
@ErnestStaug what is the source JS error that is leading to your crash? I'm curious if the same would cause my app to crash as well. Is `Sentry.captureException` in your `SentryIonicErrorHandler` reporting the error what leads to the crash?

**Comment by guv3n** [comment]
We have the same problem here on iOS

Because we want to be able to activate/deactivate the Sentry tracking remotely, we use the beforeSend to filter errors.

As the documentation says : https://docs.sentry.io/error-reporting/configuration/filtering/?platform=javascript

> If you return null, the event will be discarded.

```
Sentry.init({ 
  beforeSend: function(event){
    if (condition) 
      return event; 
    return null;
   },
  dsn: ***
});
```

It works well on Android, but on iOS the app simply crashes.

> NSInvalidArgumentException UICompatibilityInputViewController

Did you find a workaround ?
