### ISSUE TITLE
Target lowest possible cordova to stay through to v10

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cordova#186]
This should resolve:

https://github.com/getsentry/sentry-cordova/issues/126

**Comment by jennmueng** [comment]
Need to investigate and go through the issues if the large bump is actually required, however as opposed to what we thought we're still requiring a minimum of 7.0.0 and not 8.0.0:
https://github.com/getsentry/sentry-cordova/blob/b6e40a9c61618d12e84a08573e7507217e6ad207/plugin.xml#L16-L17

If the bump to 10/9 is not required, we need to investigate if the bump to 8 is actually required, if yes we should fix the above line to actually be 8.0.0 like the comment says, otherwise we leave it at 7 and fix that comment to clear up the confusion.

**Comment by bruno-garcia** [comment]
Sounds good.

The goal is to get to the minimum required version we need to get users on version 9 and 10 to work with Sentry. Given the bug reports of incompatibility. If it works with Cordova 7 or higher, that's ideal.

**Comment by jennmueng** [comment]
Closing this for now as it seems to work fine on my tests with every version from v7-10, please reopen or if anyone runs into issues, let us know.
