### ISSUE TITLE
Installation with on-premise Sentry

### ISSUE THREAD

**Issue by y-lohse** [getsentry/sentry-cordova#30]
Hi,
I'm glad to see Sentry is now working on an official plugin for Cordova!

Unfortunately, I ran into some problems trying to use it. When I run `cordova plugin add @sentry/cordova`, it automatically launches the wizard and tries to connect me to the official Sentry instance, but we have our own instance on premise so that doesn't work.
So I disabled the wizard and ran the installation again, but during the iOS installation I got the following error:

```
Failed to install 'sentry-cordova': Error: ENOENT: no such file or directory, open '/Users/yannick/Code/…/plugins/sentry-cordova/sentry.properties'
```
 

I assumed this file is supposed to be created by the wizard, so I tried running it manually. It seemed to work, but I have no idea where all the information I entered went. When I tried to run `cordova prepare`, I received the missing `sentry.properties` error again.

So I have a few questions:

- Am I doing something wrong?
- Is there a way to pass options to the sentry wizard when running `cordova add plugin` / `cordova prepare`?
- Where is the configuration stored? I need to add it to version control somehow. (edit: I see the DSN is set up [here](https://github.com/getsentry/sentry-cordova/blame/master/docs/index.rst#L42) as well, can that replace the wizard configuration?)

Cheers,
Yannick

**Comment by HazAT** [comment]
Hey,

Thanks for using Sentry, if your on prem installation is new enough, you can run the wizard and pass in the url of your installation.

https://github.com/getsentry/sentry-wizard#options

Otherwise, you can always create the `sentry.properties` manually there are many references in our docs what has to go in there:
eg.: https://docs.sentry.io/clients/java/modules/android/#gradle-integration
