### ISSUE TITLE
Remove plugin

### ISSUE THREAD

**Issue by ThomasKientz** [getsentry/sentry-cordova#37]
How can I remove the plugin ?

I am prompt by the Sentry wizard..

```
pc41:Croustillant-Ionic thomas$ cordova plugin rm sentry-cordova
no URL provided, fallback to https://sentry.io/
Running Sentry Wizard...
version: 0.9.3 | sentry-cli version: 1.30.3
Please copy/paste your organization slug
It can be found in the url https://sentry.io/organization_slug/project_slug
? Organization Slug: 
```

**Comment by HazAT** [comment]
So it works for me, what version of cordova are you running?

```
➜ cordova plugin rm sentry-cordova
no URL provided, fallback to https://sentry.io/
Running Sentry Wizard...
version: 0.9.3 | sentry-cli version: 1.30.1

😢  Successfully removed Sentry from your project 😢
Uninstalling sentry-cordova from ios
Removing "sentry-cordova"
Removing plugin sentry-cordova from config.xml file...
Removing sentry-cordova from package.json
```

**Comment by ThomasKientz** [comment]
Cordova 8.0.0

Le mar. 27 mars 2018 à 16:07, Daniel Griesser <notifications@github.com> a
écrit :

**Comment by ThomasKientz** [comment]
Finally made it, it looks like I had to first set up the project (add Organization Slug, Project Slug, DSN, Auth Token) in order to remove the plugin (its was not necessary for adding the plugin though)... This plugin is tied with the sentry cli and "complicates" things. I will use Sentry only in JS with raven, cause I don't see the benefits of using a cordova plugin atm. Will keep an eye on the repo !

**Comment by HazAT** [comment]
OK, I see your point but to clear things up, the Cordova plugin is also able to track native crashes which you cannot do with only raven-js.
In order to have a correct stacktrace showing up in Sentry, we need the user to upload the source map and debug symbols of your app, that's why we have the wizard and sentry-cli to help you with that.

Ultimately it's up to you but we always strive to deliver the best user experience possible even though there are many complicated tasks that run the background to make everything work correctly.

**Comment by alexhisen** [comment]
The fact that you have to provide all that info just to remove the plugin is crazy!

**Comment by HazAT** [comment]
The `sentry-wizard` shouldn't ask for anything when removing the plugin.
If it does, it's a bug.
