### ISSUE TITLE
[Feature request] Offline error catching support

### ISSUE THREAD

**Issue by zabojad** [getsentry/sentry-cordova#56]
One big difference between the web and the cordova contexts is that even though we are using the same languages and techs (js, css, html...), we are very often working in a offline of semi-offline environment with Cordova apps.

It would thus be very logical that this plugin caches the errors catch when the cordova app is offline in order to send them to Sentry another day (as soon as it gets back a network connection).

When first "discovering" this plugin, I thought it was already the case actually...

**Comment by HazAT** [comment]
So this should already work for iOS, for Android not yet but we are on it.

**Comment by zabojad** [comment]
OK, then I'm really looking forward to have it on Android too... Note as soon as we have that + the fixes of the other bugs I've reported, we will adopt cordova sentry in several of our cordova applications...

**Comment by pbirsinger** [comment]
For us, sentry will often crash our ios app if it tries to send an error when offline. Does no one else get this error?

```
Application threw exception NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
```

**Comment by HazAT** [comment]
@pbirsinger This only happens when you are offline? 
This error looks like that you try to set `null` as a value in extra or something, I am pretty sure that has nothing to do with offline caching.

**Comment by tigrannajaryan** [comment]
@HazAT 
We see the same error when sending the event, not sure if it is because of being offline or no (this comes from live production, not a controlled environment that I can reproduce):
```
Application threw exception NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
```

The call stack shows just one entry:
```
0x1000e0fa0__27-[SentryCordova sendEvent:]_block_invoke <redacted>/Plugins/sentry-cordova/SentryCordova.m:54
```
This is with sentry-cordova version 0.10.2.

Is it worth reporting this as a separate issue?

**Comment by ingljo** [comment]
We also get this error when trying to capture exception when the app is offline.
Using sentry-cordova version 0.13.1.

2018-12-20 13:56:18.884737+0100 [3484:2262287] CRASH: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0] Stack Trace: (
	0   CoreFoundation                      0x000000020d747eb8 <redacted> + 252
	1   libobjc.A.dylib                     0x000000020c919a40 objc_exception_throw + 56
	2   CoreFoundation                      0x000000020d6bf470 _CFArgv + 0
	3   CoreFoundation                      0x000000020d645a60 <redacted> + 352
	4   CoreFoundation                      0x000000020d6365a4 <redacted> + 64
	5   Sentry                              0x00000001010ec6d4 +[SentryJavaScriptBridgeHelper parseRavenFrames:] + 920
	6   Sentry                              0x00000001010ed828 +[SentryJavaScriptBridgeHelper createSentryEventFromJavaScriptEvent:] + 2032
	7    0x0000000100b29584 __27-[SentryCordova sendEvent:]_block_invoke + 152
	8   libdispatch.dylib                   0x0000000101193824 _dispatch_call_block_and_release + 24
	9   libdispatch.dylib                   
2018-12-20 13:56:18.909926+0100 regObs[3484:2261426] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
[3484:2261131] Task <948CD3BF-E5B5-4CAB-9871-DD4EFB8259FE>.<1> HTTP load failed (error code: -1009 [1:50])
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by AgDude** [comment]
@HazAT Any update on offline support for android? We may have someone on our team able to contribute if that can help move this along.

**Comment by jscti** [comment]
I confirm that passing null as a value for a key in "extra" crash on IOS, which is funny for a "captureException" method ...

**Comment by bruno-garcia** [comment]
It'll be done on the next release

**Comment by jbm1991** [comment]
@bruno-garcia that's great news that this will be implemented in the next release - do you know roughly when that might be? Days/weeks/months?

**Comment by jennmueng** [comment]
@jbm1991 This has been implemented in the latest release candidate.

**Comment by bruno-garcia** [comment]
We'll ship 1.0.0 soon
