### ISSUE TITLE
Default release version

### ISSUE THREAD

**Issue by alexbonhomme** [getsentry/sentry-cordova#6]
Hey,

The release version seems to be automatic and a random string in `index.html`. 
The doc says 
```
Note that we try to set the release dynamically in the index.html but if it fails you should call setRelease.
```

But `setRelease()` is called in the app code and `sentry-cli` has already uploaded the sourcemaps with the randomly generated id.

I think that it would be better if the `sentry-cli` get the release id from version in `package.json` or `config.xml`.

See ya!

**Comment by HazAT** [comment]
Hey @alexbonhomme,
So the release system is a bit complicated, only when we create a sha1 hash over all related JS files we can make sure that we have unique releases since people do not tend to bump their version in the Xcode project/package.json always and often.

For now, we are not gonna change this since the important version is the checksum over JS.

**Comment by alexbonhomme** [comment]
@HazAT Ok, but how could I manage my release if I can't configure the release name before the sourcemaps uploads ? Currently, I have the following procedure with the Raven package : 

- I builds my app to get source map files
- I uploads my source map files through the API with a release name who's basically my version number
- Then I put my app in production

With this plugin I can't control my release name and releases with random string are uploaded at each build of my app. That's not really convenient.

At least, I would like to disable the auto upload of source maps and uploads it manually like I do it with the current implementation.
